version: '3'
networks:
  micro-videos-app:
services:
  app:
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    container_name: micro-videos-app
    volumes:
      - .:/home/node/app
    networks:
      - micro-videos-app